### ISSUE TITLE
Webpack 4 / Angular 6

### ISSUE THREAD

**Issue by Justus-Maier** [qdouble/angular-webpack-starter#326]
Changes should be basic, I have had some success with the @ngtools/webpack beta.6 without AT-loader..

@qdouble what are your plans on updating this starter?

**Comment by Justus-Maier** [comment]
Maybe it would be possible to merge -aot.ts files with their non-aot correspondants? I've read about it, but haven't been successful removing them from an old setup.
E.g. this starter: https://github.com/wizardnet972/universal-seed does AOT compilation without those -aot.ts files.

**Comment by qdouble** [comment]
I haven't looked into it yet, but will start looking into it soon

**Comment by ElderJames** [comment]
Angular 6 and Material 6 have been released!

**Comment by qdouble** [comment]
@Justus-Maier @ElderJames  It took me a while since I've been very busy, but I've updated Angular and Webpack. Just let me know if there are any issues.

**Comment by Phoscur** [comment]
got this when trying to run e2e tests:
```
E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
e2e\app.e2e.ts (12,29): Argument of type 'string' is not assignable to parameter of type 'Expected<Promise<string>>'. (2345)
    at getOutput (C:\Projects\my-awesome-site\node_modules\ts-node\src\index.ts:330:15)
    at Object.compile (C:\Projects\my-awesome-site\node_modules\ts-node\src\index.ts:518:11)
    at Module.m._compile (C:\Projects\my-awesome-site\node_modules\ts-node\src\index.ts:403:43)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Projects\my-awesome-site\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
[19:22:59] E/launcher - Process exited with error code 100
```

And there is still a server.aot.ts with "broken import" (vscode), and the sibling server.ts with an unused import. Can you reduce those?
Related Question: Is it possible to reproduce the "27kb HelloWorld" and deliver or build a static (universal rendered) application? There is a lot of undocumented npm commands...

**Comment by qdouble** [comment]
@Phoscur  I'll try to look into the tests this week. I haven't really been able to use Universal in my real world apps, so that's why that has been lagging behind. I'll checkout the issues with it, but you can submit a pull request for improvements.
