### ISSUE TITLE
Getting "Cannot find module 'zone.js/dist/zone-node'" when deploying on production server

### ISSUE THREAD

**Issue by tonihuang** [qdouble/angular-webpack-starter#330]
Hi there,

Thank you for the great starter template!
I have been using it to create application and when i'm about to deploy to production server i get "Cannot find module 'zone.js/dist/zone-node'. The steps that i did was:
1. yarn universal
2. copy dist/ and dll/ folder to server
3. Run`node dist/server.js`
The fuill stacktrace is as below
Error: Cannot find module 'zone.js/dist/zone-node'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.zone.js/dist/zone-node (/var/.../myapp/dist/server.js:9138:18)
    at __webpack_require__ (/var/.../myapp/dist/server.js:20:30)
    at Object.<anonymous> (/var/.../myapp/dist/server.js:8647:130)
    at Object../src/server.ts (/var/.../myapp/dist/server.js:8711:30)
    at __webpack_require__ (/var/.../myapp/dist/server.js:20:30)
    at /var/.../myapp/dist/server.js:63:18

I can run it on the generated server.js in local but not on server. Any help will be appreciated. Thanks!

**Comment by SamuelThomas78** [comment]
Hi,
I have same problem did you find a solution ?

**Comment by tonihuang** [comment]
Hi Samuel,

I ended up performing yarn install on server to have the package installed on server.

**Comment by nagarajukmenlo** [comment]
Hi, 
When we run node dist/server.js I am getting following error:

Error: Invalid provider for undefined. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.
    at syntaxError (C:\Users\nagaraajuk\Desktop\New folder\dist\node_modules\@angular\compiler\bundles\compiler.umd.js:287:21)

Node Version: 9.11.0
Webpack version: 4.0.0
NPM version: 5.6.0

Please help us to resolve the above issue. 

Thanks.

**Comment by nagarajukmenlo** [comment]
Hi All,

I got a fix for the above-mentioned issue.

I have added below lines in webpak.config.ts 

"module": {
    "rules": [
      {
        "enforce": "pre",
        "test": /\.js$/,
        "loader": "source-map-loader",
        "exclude": [
          // instead of /\/node_modules\//
          path.join(process.cwd(), 'node_modules')
        ]
      },

**Comment by abelokon0711** [comment]
@nagarajukmenlo unfortunately your solution did not help. we get still the same error

**Comment by ohabash** [comment]
I have the same problem. The problem started when i was trying to fix another [problem](https://stackoverflow.com/questions/53577473/firebase-admin-throws-errors-when-building-server-npm-run-webpackserver) . My universal app kept failing during build but doing the following in `webpack.server.config.js` allowed the app to build. But cause the same problem you guys described above.

`const nodeExternals = require('webpack-node-externals');`

```
module.exports = {
...
   externals: [nodeExternals()],
...
}
```

Did you guys find a solution? are you still working on it?
