### ISSUE TITLE
Issue with npm/Yarn Install

### ISSUE THREAD

**Issue by braino15** [qdouble/angular-webpack-starter#335]
Hi,

After cloning material branch with and without universal support, when I do npm Install or yarn install, getting the following error

PRODUCTION BUILD:  false
AOT:  false
BUILDING DLLs
 11% building modules 11/11 modules 0 activeError: No module factory available for dependency type: ContextElementDependency
    at addDependency (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:417:12)
    at iterationOfArrayCallback (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:435:5)
    at iterationOfArrayCallback (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:438:5)
    at Compilation.processModuleDependencies (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:446:4)
    at afterBuild (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:568:15)
    at buildModule.err (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:612:11)
    at callback (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:364:5)
    at module.build.error (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:404:12)
    at resolveDependencies (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\ContextModule.js:272:4)
    at ContextModule.result.resolveDependencies (D:\adPlanner\angular-webpack-starter\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:649:13)
    at ContextModule.build (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\ContextModule.js:195:8)
    at Compilation.buildModule (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:369:10)
    at factory.create (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\Compilation.js:595:14)
    at hooks.afterResolve.callAsync (D:\AdPlanner\angular-webpack-starter\node_modules\webpack\lib\ContextModuleFactory.js:157:16)
    at _fn0 (eval at create (D:\AdPlanner\angular-webpack-starter\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:14:1)
    at done.then (D:\adPlanner\angular-webpack-starter\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:652:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE

Node version: V: 8.11.3
npm : v5.6.0
windows 10 (64 bit)

There are No multiple versions of webpack installed (npm ls webpack output). Also, tried various options like installing webpack globally and removing it from package.json DevDependencies, clearing cache and doing npm/yarn install, deleting package.json before fresh install. (like mentioned here https://stackoverflow.com/questions/46809626/angular-no-module-factory-available-for-dependency-type-contextelementdependenc)

Infact tried locking down exact version by removing ~ ^ sign for each package , for semantic versioning but no luck. Can you please help me with this? Thanks.

**Comment by braino15** [comment]
Any help around this? Thanks.

**Comment by braino15** [comment]
.
